// Should be in sync with the prism schema
export enum QuestionType {
  ARRAY = 'ARRAY',
  SORTING = 'SORTING',
  PATH_FINDING = 'PATH_FINDING',
  GRAPH = 'GRAPH',
  STRING = 'STRING',
  TREE = 'TREE',
  LINKED_LIST = 'LINKED_LIST',
  DYNAMIC_PROGRAMMING = 'DYNAMIC_PROGRAMMING',
  RECURSION = 'RECURSION',
  STACK = 'STACK',
  QUEUE = 'QUEUE',
  HEAP = 'HEAP',
  HASHING = 'HASHING',
}

export enum QuestionField {
  BANKING = 'BANKING',
  GAME_DEVELOPMENT = 'GAME_DEVELOPMENT',
  BASIC = 'BASIC',
  MOSTLY_USED = 'MOSTLY_USED',
  DATA_SCIENCE = 'DATA_SCIENCE',
  WEB_DEVELOPMENT = 'WEB_DEVELOPMENT',
  MOBILE_DEVELOPMENT = 'MOBILE_DEVELOPMENT',
  NETWORKING = 'NETWORKING',
  OPERATING_SYSTEMS = 'OPERATING_SYSTEMS',
  DATABASES = 'DATABASES',
}

export enum QuestionDifficulty {
  EASY = 'EASY',
  MEDIUM = 'MEDIUM',
  HARD = 'HARD',
  VERY_HARD = 'VERY_HARD',
  EXTREME = 'EXTREME',
}