import './globals.css';

import { ClerkProvider } from '@clerk/nextjs';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { ThemeProvider } from '@/lib/components';
import { NavBar } from '@/lib/components/navigation/nav-bar';
import { Toaster } from '@/lib/components/ui/sonner';
import { cn } from '@/lib/utils';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={cn(inter.className)}>
          <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
            <div className="relative grid h-screen grid-rows-[auto_1fr]">
              <div className="sticky left-0 right-0 top-0 z-10">
                <NavBar />
              </div>
              <div className="h-full overflow-y-auto">{children}</div>
            </div>
            <Toaster richColors />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
